<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="1"
            failures="0"
            tests="1">

  <testsuite name="profile"
    errors="1" failures="0" hostname="" id="" package="profile" skipped="0"
    tests="1" time="0.01600" timestamp="Mon, 25 Mar 2019 15:58:37 GMT">
  
    <testcase name="log in/out of created account" classname="profile" time="0.01600" assertions="0">
    </testcase>
  

  
    <system-err>
        Error while running [Profile / log in/out of created account]:

  TypeError: Cannot read property &#39;1&#39; of undefined
    at Object.log in/out of created account (C:\Users\Thomas\DevMountain\Yoodlize\tests\profile.js:39:49)
    at Module.call (C:\Users\Thomas\AppData\Roaming\npm\node_modules\nightwatch\lib\runner\module.js:62:34)
    at C:\Users\Thomas\AppData\Roaming\npm\node_modules\nightwatch\lib\runner\testcase.js:70:29
    at _fulfilled (C:\Users\Thomas\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\Thomas\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\Thomas\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:796:13)
    at C:\Users\Thomas\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:556:49
    at runSingle (C:\Users\Thomas\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:137:13)
    at flush (C:\Users\Thomas\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    </system-err>
  

  
  </testsuite>
</testsuites>
